# Title of the document
title: "Pandas Profiling Report"

html:
# Minify the html
    minify_html: True

# Offline support
    use_local_assets: True

# If True, single file, else directory with assets
    inline: True

# Show navbar
    navbar_show: True

# For internal use
    file_name: None

# Styling options for the HTML report
    style:
      theme: None
      logo: ""
      primary_color: "#337ab7"
      full_width: False
      
      
# Per variable type description settings
vars:
    num:
        quantiles:
              - 0.05
              - 0.25
              - 0.5
              - 0.75
              - 0.95
        skewness_threshold: 20
        low_categorical_threshold: 10s
        
# Plot-specific settings
plot:
# Image format (svg or png)
    image_format: "svg"
    dpi: 800

    scatter_threshold: 1000

    correlation:
        cmap: 'RdBu'
        bad: '#000000'

    missing:
        cmap: 'RdBu'
    
html:
# Minify the html
    minify_html: True

# Offline support
    use_local_assets: True

# If True, single file, else directory with assets
    inline: True

# Show navbar
    navbar_show: True

# For internal use
    file_name: None

# Styling options for the HTML report
    style:
      theme: None
      logo: ""
      primary_color: "#337ab7"
      full_width: False
